language: java
jdk:
  - oraclejdk13
  - oraclejdk12
  - oraclejdk11
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8


matrix:
   include:
     - os: linux
     - dist: precise
     - os: linux
     - dist: trusty

script:      
  - java -jar Exercise.jar -v ISDI 1 99999 4 38638da3a8e43673432fcd84279d20c7
